"""HTTP orchestration for the standalone adapter service."""

from __future__ import annotations

import dataclasses
import time
from typing import Any

from aiohttp import web

from .models import Generation, NormalizedRequest, OutputParserConfig, ParsedOutput
from .parsing import parse_model_output
from .protocols import (
    anthropic_response,
    anthropic_stream,
    normalize_anthropic,
    normalize_openai,
    openai_response,
    openai_stream,
)
from .recording import JsonlRecorder
from .sglang import SGLangClient, SGLangError


class AdapterServer:
    """Expose OpenAI and Anthropic-compatible APIs backed by one SGLang server.

    A request is normalized into a common representation, generated by SGLang,
    recorded as one trajectory turn, then rendered back to its source protocol.
    """

    def __init__(
        self,
        *,
        tokenizer: Any,
        sglang_url: str,
        output_dir: str,
        parser_config: OutputParserConfig | None = None,
    ) -> None:
        self.tokenizer = tokenizer
        self.sglang = SGLangClient(sglang_url)
        self.recorder = JsonlRecorder(output_dir)
        self.parser_config = parser_config or OutputParserConfig()
        self.app = web.Application(client_max_size=64 * 1024 * 1024)
        self.app.router.add_get("/healthz", self._health)
        self.app.router.add_get("/v1/models", self._health)
        self.app.router.add_post("/v1/chat/completions", self._openai)
        self.app.router.add_post("/v1/messages", self._anthropic)
        self.app.router.add_post("/v1/messages/count_tokens", self._count_tokens)

    async def _health(self, request: web.Request) -> web.Response:
        return web.json_response({"ok": True})

    async def _count_tokens(self, request: web.Request) -> web.Response:
        await request.read()
        return web.json_response({"input_tokens": 0})

    async def _openai(self, request: web.Request) -> web.StreamResponse:
        result = await self._run(request, normalize_openai)
        response = openai_response(result.spec, result.generation, result.parsed)
        return await openai_stream(request, response) if result.spec.stream else web.json_response(response)

    async def _anthropic(self, request: web.Request) -> web.StreamResponse:
        result = await self._run(request, normalize_anthropic)
        response = anthropic_response(result.spec, result.generation, result.parsed)
        return await anthropic_stream(request, response) if result.spec.stream else web.json_response(response)

    async def _run(self, request: web.Request, normalizer) -> "TurnResult":
        body = await request.json()
        spec = normalizer(request, body)
        prompt_token_ids = self._render_prompt(spec)
        try:
            generation = await self.sglang.generate(
                prompt_token_ids=prompt_token_ids,
                sampling_params=spec.sampling_params,
                routing_key=spec.trajectory_id,
            )
        except SGLangError as error:
            raise web.HTTPBadGateway(text=str(error)) from error
        raw_output = self.tokenizer.decode(generation.output_token_ids, skip_special_tokens=False) if generation.output_token_ids else ""
        parsed = parse_model_output(raw_output, spec.tools, self.parser_config)
        await self.recorder.write(
            spec.trajectory_id,
            {
                "schema_version": 1,
                "recorded_at": time.time(),
                "protocol": spec.protocol,
                "trajectory_id": spec.trajectory_id,
                "model": spec.model,
                "request_id": generation.request_id,
                "request": spec.request,
                "normalized_messages": spec.messages,
                "tools": spec.tools,
                "parser_config": dataclasses.asdict(self.parser_config),
                "sampling_params": spec.sampling_params,
                "prompt_token_ids": generation.prompt_token_ids,
                "output_token_ids": generation.output_token_ids,
                "output_logprobs": generation.output_logprobs,
                "raw_output": raw_output,
                "parsed_output": dataclasses.asdict(parsed),
                "finish_reason": generation.finish_reason,
            },
        )
        return TurnResult(spec=spec, generation=generation, parsed=parsed)

    def _render_prompt(self, spec: NormalizedRequest) -> list[int]:
        encoded = self.tokenizer.apply_chat_template(
            spec.messages,
            tools=spec.tools,
            tokenize=True,
            add_generation_prompt=True,
        )
        token_ids = encoded["input_ids"] if hasattr(encoded, "__getitem__") and not isinstance(encoded, list) else encoded
        return list(token_ids)


@dataclasses.dataclass(frozen=True)
class TurnResult:
    spec: NormalizedRequest
    generation: Generation
    parsed: ParsedOutput
